version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  assignees:
    - "ken-matsui"
  reviewers:
    - "ken-matsui"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
  assignees:
    - "ken-matsui"
  reviewers:
    - "ken-matsui"
