query getAllPackages($limit: Int!, $offset: Int!) @cached(ttl: 600) {
  packages(limit: $limit, offset: $offset, order_by: {name: asc, version: asc, id: asc}) {
    authors
    description
    edition
    id
    license
    metadata
    name
    published_at
    readme
    repository
    sha256sum
    version
  }
}
