apiVersion: v1
kind: Service
metadata:
  name: poac-pm-cluster
  labels:
    name: poac-pm-cluster
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 4000
    protocol: TCP
  selector:
    name: poac-pm-cluster
