name: Elm CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action: [ lint, test, build ]
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14.x

      - run: npm ci
      - run: npm run ${{ matrix.action }}

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14.x

      - run: npm ci
      - run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
